const CONST_MIME_APPLICATION_JSON = 'application/json';
const CONST_MIME_APPLICATION_OCTET_STREAM = 'application/octet-stream';
const CONST_MIME_APPLICATION_X_WWW_FORM_URLENCODED =
  'application/x-www-form-urlencoded';
const CONST_MIME_IMAGE_GIF = 'image/gif';
const CONST_MIME_IMAGE_JPEG = 'image/jpeg';
const CONST_MIME_IMAGE_PNG = 'image/png';
const CONST_MIME_IMAGE_SVG_XML = 'image/svg+xml';
const CONST_MIME_IMAGE_WEBP = 'image/webp';
const CONST_MIME_IMAGE_X_ICON = 'image/x-icon';
const CONST_MIME_TEXT_CSS = 'text/css';
const CONST_MIME_TEXT_HTML = 'text/html';
const CONST_MIME_TEXT_JAVASCRIPT = 'text/javascript';
const CONST_MIME_TEXT_PLAIN = 'text/plain';

export {
  CONST_MIME_APPLICATION_JSON,
  CONST_MIME_APPLICATION_OCTET_STREAM,
  CONST_MIME_APPLICATION_X_WWW_FORM_URLENCODED,
  CONST_MIME_IMAGE_GIF,
  CONST_MIME_IMAGE_JPEG,
  CONST_MIME_IMAGE_PNG,
  CONST_MIME_IMAGE_SVG_XML,
  CONST_MIME_IMAGE_WEBP,
  CONST_MIME_IMAGE_X_ICON,
  CONST_MIME_TEXT_CSS,
  CONST_MIME_TEXT_HTML,
  CONST_MIME_TEXT_JAVASCRIPT,
  CONST_MIME_TEXT_PLAIN,
};
