const CONST_STATUS_HTTP = {
  BAD_REQUEST: 400,
  CONFLICT: 409,
  FORBIDDEN: 403,
  FOUND: 302,
  INTERNAL_SERVER_ERROR: 500,
  NO_CONTENT: 204,
  NOT_FOUND: 404,
  OK: 200,
  PAYLOAD_TOO_LARGE: 413,
  SEE_OTHER: 303,
  UNAUTHORIZED: 401,
} as const;

const CONST_REASON_STATUS_HTTP = {
  [CONST_STATUS_HTTP.BAD_REQUEST]: 'Bad Request',
  [CONST_STATUS_HTTP.CONFLICT]: 'Conflict',
  [CONST_STATUS_HTTP.FORBIDDEN]: 'Forbidden',
  [CONST_STATUS_HTTP.FOUND]: 'Found',
  [CONST_STATUS_HTTP.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
  [CONST_STATUS_HTTP.NO_CONTENT]: 'No Content',
  [CONST_STATUS_HTTP.NOT_FOUND]: 'Not Found',
  [CONST_STATUS_HTTP.OK]: 'OK',
  [CONST_STATUS_HTTP.PAYLOAD_TOO_LARGE]: 'Payload Too Large',
  [CONST_STATUS_HTTP.SEE_OTHER]: 'See Other',
  [CONST_STATUS_HTTP.UNAUTHORIZED]: 'Unauthorized',
} as Record<number, string>;

export { CONST_REASON_STATUS_HTTP, CONST_STATUS_HTTP };
