const CONST_STATUS_HTTP = {
  BAD_REQUEST: 400,
  FORBIDDEN: 403,
  FOUND: 302,
  INTERNAL_SERVER_ERROR: 500,
  NOT_FOUND: 404,
  OK: 200,
  PAYLOAD_TOO_LARGE: 413,
} as const;

const CONST_REASON_STATUS_HTTP = {
  [CONST_STATUS_HTTP.BAD_REQUEST]: 'Bad Request',
  [CONST_STATUS_HTTP.FORBIDDEN]: 'Forbidden',
  [CONST_STATUS_HTTP.FOUND]: 'Found',
  [CONST_STATUS_HTTP.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
  [CONST_STATUS_HTTP.NOT_FOUND]: 'Not Found',
  [CONST_STATUS_HTTP.OK]: 'OK',
  [CONST_STATUS_HTTP.PAYLOAD_TOO_LARGE]: 'Payload Too Large',
} as Record<number, string>;

export { CONST_REASON_STATUS_HTTP, CONST_STATUS_HTTP };
